### PR TITLE
Fix running tests with OpenMPI

### PR DESCRIPTION
**Pull request by pjgeorg**
This only solves the issue for running the tests, not generic. A better
soltion to this issues is adding the following lines to the python code
before using MPI:

import ctypes
ctypes.CDLL("libmpi.so", mode=ctypes.RTLD_GLOBAL)

Or even better, add this line:
from mpi4py import MPI

### CODE REVIEW

**Comment by pjgeorg** [comment]
## Running with more than one process
Tests simply hang. I guess due to a deadlock.

## Running with only one process
Still using mpirun, the tests at least now fail immediately with a segfault.
Two guesses:
- It is simply not working at all and would also fail trying to run a gcc + openMPI (<3.0) build locally. Has anyone ever run this configuration? Intel MPI is a very bad option for testing...
- Not working in github docker container due to some of Grid's MPI SHM "workarounds" simply not working within a docker container at all or only in github's containers.

Moving forward it seems to be best to work in this order:
- Get non MPI build to pass all tests
- Get MPI build using only 1 process to pass all tests
- Start working on fixing MPI builds with more than 1 process to pass all tests

Commit 0059e31 (or one of the better options mentioned in the first comment) will be required anyway.

@aragon999 and @lehner: Thoughts?

PS: As long as the CI jobs assiciated with this pull request are still running (should be killed after ~6 hours) you can simply look at the same jobs running on my fork: https://github.com/pjgeorg/gpt/actions

**Comment by lehner** [comment]
I just compiled with gcc/6.4.0 and no mpi:

../configure --enable-precision=double --enable-simd=AVX2 --enable-comms=none --enable-shm=shmget --enable-shmpath=/dev/hugepages CXX=g++ CXXFLAGS=-fPIC --with-lime=/sdcc/u/clehner/usqcd/lime CC=gcc --no-create --no-recursion

and then compiled cgpt and first saw a segfault as you described.  I noticed that some symbols were not properly created, so I deleted the expression_*mul.o and linear_combination.o and compiled again.  After that I had no segfault and all tests passed.

I am running out of time for right now to spend on this but we first need to make this behavior reproducible and figure out exactly what is triggering this.

**Comment by aragon999** [comment]
So locally I have currently can reproduce both bugs, so when running with 1 rank, I have the same segfaults as here: https://github.com/pjgeorg/gpt/runs/722704780?check_suite_focus=true

When I run with more than one rank I have the same Deadlocks as here: https://github.com/pjgeorg/gpt/runs/721765963?check_suite_focus=true

openmpi - 4.0.3
clang - 10.0.0

I will try to find some time to look into this.

Edit: I think also the order of TODOs is also reasonable, such that people can run the code locally, and test stuff on smaller test projects.

**Comment by pjgeorg** [comment]
Compiling grid and cgpt without MPI on one of my machines (F31, gcc 9.3, plain default grid configure, only adding -fPIC), running some of the tests fail with a segfault...

To better track this I started working on this CI issues a little bit. To make it easier for me I started of a new branch based on Stefan's https://github.com/ssolbUR/gpt/tree/feature/setup including the open Pull Request (https://github.com/ssolbUR/gpt/pull/1), merged pull request #2, and merged Max' current wip/restruture-builds-as-packages.

Link to new branch: https://github.com/pjgeorg/gpt

(It is currently building grid....)

Hence closing this pull request for now.

**Pull request closed without merging**
